// <auto-generated />
using System;
using Huerto_Del_valle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Huerto_Del_valle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210605040853_m2Proforma")]
    partial class m2Proforma
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Proyecto_Prog1.Models.Proforma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProductoIdid")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("ProductoIdid");

                    b.ToTable("t_proforma");
                });


            modelBuilder.Entity("Proyecto_Prog1.Models.Proforma", b =>
                {
                    b.HasOne("Huerto_Del_valle.Models.Producto", "ProductoId")
                        .WithMany()
                        .HasForeignKey("ProductoIdid");

                    b.Navigation("ProductoId");
                });
#pragma warning restore 612, 618
        }
    }
}
